[package]
name = "quickgiflick"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A lightweight Windows GIF recorder powered by ScreenDelta."

[dependencies]
gif = "0.13.3"
screendelta = { git = "https://github.com/ARTS-Night/ScreenDelta.git", rev = "ac2f7d4ee43451241796d684b4d8dea5d8e7b41c" }
